---

- hosts: all
  become: true
  become_method: su
  become_flags: "--login"
  become_user: oracle
  tasks:
  - name: check existance of mount point
    command: mountpoint -q /oracle
    register: volume_stat
    failed_when: false
  - name: copy file
    copy:  
      src: LINUX.X64_193000_client.zip
      dest: /home/oracle
      mode: 0777
  - name: copy client oracle db
    unarchive: 
      src: /home/oracle/LINUX.X64_193000_client.zip 
      dest: /home/oracle
      mode: 0755
      remote_src: yes
  - name: copy response file
    copy: 
      src: oracle_client_19c.rsp 
      dest: /home/oracle 
      mode: 0777
  - name: Install oracle client
    command: "/oracle/client/runInstaller -silent -showProgress -ignorePrereq -ignoreSysPrereqs -waitforcompletion -responseFile /oracle/oracle_client_19c.rsp"
    register: client_runinstaller_output
    failed_when: "'Successfully Setup Software' not in client_runinstaller_output.stdout"
